import path from "path";
import { glob } from "glob";
import { writePrettyFile } from "./utils/svg.ts";

const ROOT = process.cwd();
const ICON_DIR = path.join(ROOT, "iconPack", "icons");
const OUT_FILE = path.join(ROOT, "iconPack", "iconMap.ts");

function toKebab(name: string) {
  return name
    .replace(/Icon$/, "")
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .toLowerCase();
}

async function run() {
  const files = glob.sync("*.tsx", { cwd: ICON_DIR });
  const imports = files.map((f) => f.replace(/\.tsx$/, ""));
  const importLine = `import { ${imports.join(", ")} } from './index';`;
  const mapEntries = files
    .map((f) => {
      const comp = f.replace(/\.tsx$/, "");
      const key = toKebab(comp);
      return `  '${key}': ${comp},`;
    })
    .join("\n");
  const content = `// Auto-generated by scripts/generate-iconmap.ts
${importLine}

export const iconMap = {
${mapEntries}
} as const;

export type IconName = keyof typeof iconMap;
`;
  await writePrettyFile(OUT_FILE, content, "babel-ts");
  console.log("✅ iconMap.ts generated");
}

run().catch(console.error);
