import { fileURLToPath } from "url";
import path from "path";
import fs from "fs-extra";
import { transform } from "@svgr/core";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const INPUT_DIR = path.resolve(__dirname, "../src/icons/svg");
const OUTPUT_DIR = path.resolve(__dirname, "../src/icons/react/icons");
const INDEX_DIR = path.resolve(__dirname, "../src/icons/react");

function toPascalCase(str) {
  return str
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join("");
}

const componentTemplate = (variables, { tpl }) => {
  return tpl`
import * as React from 'react';

interface Props extends React.SVGProps<SVGSVGElement> {
  title?: string;
}

const ${variables.componentName} = React.forwardRef<SVGSVGElement, Props>(({ title, ...props }, ref) => (
  ${variables.jsx}
));

export default ${variables.componentName};
  `;
};

async function generateIcons() {
  await fs.ensureDir(OUTPUT_DIR);
  await fs.ensureDir(INDEX_DIR);

  const files = await fs.readdir(INPUT_DIR);
  const iconMappings = [];

  for (const file of files) {
    if (!file.endsWith(".svg")) continue;

    const filePath = path.join(INPUT_DIR, file);
    const svgContent = await fs.readFile(filePath, "utf8");

    const baseName = path.basename(file, ".svg");
    const componentName = toPascalCase(baseName) + "Icon";

    const tsxCode = await transform(
      svgContent,
      {
        typescript: true,
        icon: true,
        ref: true,
        jsxRuntime: "automatic",
        template: componentTemplate,
        plugins: ["@svgr/plugin-svgo", "@svgr/plugin-jsx"],
        svgProps: {
          fill: "currentColor",
        },
        svgoConfig: {
          plugins: [
            {
              name: "preset-default",
              params: {
                overrides: {
                  removeViewBox: false,
                },
              },
            },
            {
              name: "removeAttrs",
              params: {
                attrs: "(fill|stroke)",
              },
            },
          ],
        },
      },
      { componentName }
    );

    const outputFilePath = path.join(OUTPUT_DIR, `${componentName}.tsx`);
    await fs.writeFile(outputFilePath, tsxCode, "utf8");

    console.log(`✅ ${componentName}.tsx generated successfully`);

    iconMappings.push({ key: baseName, componentName });
  }

  const indexContent = iconMappings
    .map(
      ({ componentName }) =>
        `export { default as ${componentName} } from './icons/${componentName}';`
    )
    .join("\n");

  const indexFilePath = path.join(INDEX_DIR, "index.ts");
  await fs.writeFile(indexFilePath, indexContent, "utf8");
  console.log(
    `✅ index.ts generated successfully with ${iconMappings.length} exports`
  );

  const iconMapImports = iconMappings.map((i) => i.componentName).join(", ");
  const iconNamesType = iconMappings.map((i) => `'${i.key}'`).join(" | ");
  const iconMapObject = iconMappings
    .map((i) => `  '${i.key}': ${i.componentName},`)
    .join("\n");

  const iconMapContent = `// This file is auto-generated by the icon script. Do not edit manually.

import * as React from 'react';
import { ${iconMapImports} } from './index';

export type IconName = ${iconNamesType};

export const iconMap: Record<IconName, React.FC<React.SVGProps<SVGSVGElement>>> = {
${iconMapObject}
};
`;

  const iconMapFilePath = path.join(INDEX_DIR, "iconMap.ts");
  await fs.writeFile(iconMapFilePath, iconMapContent, "utf8");
  console.log(`✅ iconMap.ts generated successfully`);
}

generateIcons().catch(console.error);
